[package]
name = "dns-over-wikipedia"
version = "0.1.0"
authors = ["Aaron Janse <aaron@ajanse.me>", "Vihan Bhargava <aa@aa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
